
module.exports.DeviceTemplateTypes = [
  {
    optValue: 'DEVICE_ABB_M4M',
    optText: 'ABB M4M Meter',
    optTextShort: 'ABB M4M',
    link: 'device-abb-m4m',    
    dataSize: 2,
  },
  {
    optValue: 'DEVICE_CIRCUTOR_AFQ',
    optText: 'Circutor AFQ Multi Function Filter Controller',
    optTextShort: 'Circutor AFQ',
    link: 'device-circutor-afq',    
    dataSize: 2,
  }, 
  {
    optValue: 'DEVICE_COMAP_INTELIGEN_200',
    optText: 'ComAp InteliGen 200 Generator Controller',
    optTextShort: 'ComAp InteliGen 200',
    link: 'device-comap-inteligen-200',    
    dataSize: 2,
  },
  {
    optValue: 'DEVICE_INTEGRA_2270',
    optText: 'Crompton Integra 2270 Meter',
    optTextShort: 'Crompton Integra 2270',
    link: 'device-crompton-integra-2270',    
    dataSize: 2,
  },
  {
    optValue: 'DEVICE_MOXA_E1210',
    optText: 'Moxa Logik E1210 IO Controller',
    optTextShort: 'Moxa E1210',
    link: 'device-moxa-e1210',    
    dataSize: 2,
  },  
  {
    optValue: 'DEVICE_SCHNEIDER_IEM3250',
    optText: 'Schneider IEM3250 and IEM3255 Meter',
    optTextShort: 'Schneider IEM3250',
    link: 'device-schneider-iem3250',    
    dataSize: 2,
  },
  {
    optValue: 'DEVICE_SCHNEIDER_POWERTAG_1P',
    optText: 'Schneider PowerTag Single Phase Meter',
    optTextShort: 'Schneider PowerTag 1P',
    link: 'device-schneider-powertag-1p',    
    dataSize: 2,
  },    
  {
    optValue: 'DEVICE_SCHNEIDER_POWERTAG_3P',
    optText: 'Schneider PowerTag Three Phase Meter',
    optTextShort: 'Schneider PowerTag 3P',
    link: 'device-schneider-powertag-3p',    
    dataSize: 2,
  },    
  {
    optValue: 'DEVICE_SCHNEIDER_POWERTAG_A9MEM1540',
    optText: 'Schneider PowerTag A9MEM1540 Meter',
    optTextShort: 'Schneider PowerTag A9MEM1540',
    link: 'device-schneider-powertag-a9mem1540',    
    dataSize: 2,
  },    
  {
    optValue: 'DEVICE_SCHNEIDER_POWERTAG_A9MEM1580',
    optText: 'Schneider PowerTag A9MEM1580 Meter',
    optTextShort: 'Schneider PowerTag A9MEM1580',
    link: 'device-schneider-powertag-a9mem1580',    
    dataSize: 2,
  },    
  {
    optValue: 'DEVICE_SOCOMEC_DIRIS_A10',
    optText: 'Socomec Diris A10 Meter',
    optTextShort: 'Socomec A10',
    link: 'device-socomec-diris-a10',    
    dataSize: 2,
  },   
];