module.exports.DeviceTemplateTypes = [
  {
    optValue: 'DEVICE_ABB_2324',
    optText: 'ABB B23 B24 Meter',
    optTextShort: 'ABB B23 B24',
    link: 'device-abb-2324',
  },
  {
    optValue: 'DEVICE_ABB_M2M',
    optText: 'ABB M2M Meter',
    optTextShort: 'ABB M2M',
    link: 'device-abb-m2m',    
  },  
  {
    optValue: 'DEVICE_ABB_M4M',
    optText: 'ABB M4M Meter',
    optTextShort: 'ABB M4M',
    link: 'device-abb-m4m',    
  },  
  {
    optValue: 'DEVICE_CARLO_EM21',
    optText: 'Carlo Gavazzi EM21 Meter',
    optTextShort: 'Carlo EM21',
    link: 'device-carlo-em21',    
  },  
  {
    optValue: 'DEVICE_CARLO_EM24',
    optText: 'Carlo Gavazzi EM24 Meter',
    optTextShort: 'Carlo EM24',
    link: 'device-carlo-em24',    
  },  
  {
    optValue: 'DEVICE_CARLO_EM270_1',
    optText: 'Carlo Gavazzi EM270 Channel 1 Meter',
    optTextShort: 'Carlo EM270 CH1',
    link: 'device-carlo-em270-1',
    dataSize: 2,
  }, 
  {
    optValue: 'DEVICE_CARLO_EM270_2',
    optText: 'Carlo Gavazzi EM270 Channel 2 Meter',
    optTextShort: 'Carlo EM270 CH2',
    link: 'device-carlo-em270-2',    
    dataSize: 2,
  }, 
  {
    optValue: 'DEVICE_CIRCUTOR_AFQ',
    optText: 'Circutor AFQ Multi Function Filter Controller',
    optTextShort: 'Circutor AFQ',
    link: 'device-circutor-afq',    
    dataSize: 2,
  }, 
  {
    optValue: 'DEVICE_COMAP_INTELIGEN_200',
    optText: 'ComAp InteliGen 200 Generator Controller',
    optTextShort: 'ComAp InteliGen 200',
    link: 'device-comap-inteligen-200',    
    dataSize: 2,
  },      
  {
    optValue: 'DEVICE_CROMPTON_INTEGRA_CI3',
    optText: 'Crompton Integra CI3 Meter',
    optTextShort: 'Crompton CI3',
    link: 'device-crompton-integra-ci3',    
    dataSize: 2,
  },      
  {
    optValue: 'DEVICE_CROMPTON_INTEGRA_DL1_1',
    optText: 'Crompton Integra DL1 Channel 1 Meter',
    optTextShort: 'Crompton DL1 CH1',
    link: 'device-crompton-integra-dl1-1',    
    dataSize: 2,
  },      
  {
    optValue: 'DEVICE_CROMPTON_INTEGRA_DL1_2',
    optText: 'Crompton Integra DL1 Channel 2 Meter',
    optTextShort: 'Crompton DL1 CH2',
    link: 'device-crompton-integra-dl1-2',    
    dataSize: 2,
  },      
  {
    optValue: 'DEVICE_ELECTREX_FEMTO_D4',
    optText: 'Electrex Femto D4 Meter',
    optTextShort: 'Electrex D4',
    link: 'device-electrex-femto-d4',    
    dataSize: 2,
  },      
  {
    optValue: 'DEVICE_MOXA_E1210',
    optText: 'Moxa Logik E1210 IO Controller',
    optTextShort: 'Moxa E1210',
    link: 'device-moxa-e1210',    
    dataSize: 2,
  },  
  {
    optValue: 'DEVICE_SCHNEIDER_PM3250',
    optText: 'Schneider PM3250 and PM3255 Meter',
    optTextShort: 'Schneider PM3250',
    link: 'device-schneider-pm3250',    
    dataSize: 2,
  },    
  {
    optValue: 'DEVICE_SOCOMEC_COUNTIS_E43',
    optText: 'Socomec Countis E43 Meter',
    optTextShort: 'Socomec E43',
    link: 'device-socomec-countis-e43',    
    dataSize: 2,
  },     
  {
    optValue: 'DEVICE_SOCOMEC_DIRIS_A10',
    optText: 'Socomec Diris A10 Meter',
    optTextShort: 'Socomec A10',
    link: 'device-socomec-diris-a10',    
    dataSize: 2,
  },     
  
];